# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

RUN npm install react-scripts@3.4.1 -g --silent
#RUN npm install react-router-dom -g --silent
#RUN npm install bootstrap -g --silent
#RUN npm install react-icons -g --silent
#RUN npm install react-bootstrap -g --silent
#RUN npm i -g install --save typescript @types/node @types/react @types/react-dom @types/jest

# add app
COPY . ./

# start app
CMD ["npm", "start"]